x-bench: &bench
  working_dir: /work
  volumes:
    - .:/work

services:
  mri:
    <<: *bench
    build: { context: ., dockerfile: docker/Dockerfile.mri }
    image: rails-ruby4-bench/mri
    environment:
      BENCH_RUNTIME: mri
      RAILS_YJIT: "false"

  mri-yjit:
    <<: *bench
    image: rails-ruby4-bench/mri
    environment:
      BENCH_RUNTIME: mri-yjit

  mri-yjit-rubyopt:
    <<: *bench
    image: rails-ruby4-bench/mri
    environment:
      BENCH_RUNTIME: mri-yjit-rubyopt
      RUBYOPT: --yjit

  truffleruby:
    <<: *bench
    build: { context: ., dockerfile: docker/Dockerfile.truffleruby }
    image: rails-ruby4-bench/truffleruby
    environment:
      BENCH_RUNTIME: truffleruby
