FROM ruby:4.0.7-bookworm

ENV LANG=C.UTF-8 \
    BUNDLE_PATH=/usr/local/bundle \
    BUNDLE_JOBS=4 \
    BUNDLE_RETRY=3 \
    RAILS_ENV=production

WORKDIR /work
COPY Gemfile Gemfile.lock* ./
RUN bundle install
